name: "Construção do artefato"

on:
    push:
        branches: [ "main", "feature_docker" ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: larissagandarela
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Constrói e envia imagem docker
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: larissagandarela/projeto_go:latest,larissagandarela/projeto_go:${{ github.sha }}
      
