name: Entrega continua

on:
  workflow_call:

jobs:

  ECS:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
        
      - name: Obtendo arquivo da tarefa
        run: aws ecs describe-task-definition --task-definition my-task-definition-family --query taskDefinition > task-definition.json
      
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: my-container 
          image: ${{ steps.build-image.outputs.image }}  
          environment-variables: |
            DB_HOST=${{ secrets.DB_HOST_AWS }}
            DB_USER=${{ secrets.DB_USER_AWS }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD_AWS }}
            DB_NAME=${{ secrets.DB_NAME_AWS }}
            DB_PORT=${{ secrets.DB_PORT_AWS }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: Servico_API-Go
          cluster: API-Go
          wait-for-service-stability: true