name: Integração Contínua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Inicia o banco de dados
      run: |
        docker compose up -d postgres
        # Aguardar o banco de dados ficar disponível
        until nc -z postgres 5432; do
          echo "Aguardando banco de dados iniciar..."
          sleep 1
        done

    - name: Lint
      run: docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint golangci-lint run controllers/ database/ models/ routes/

    - name: Teste
      run: docker compose exec app go test -v main_test.go
      env:
        DB_HOST: "postgres"
        DB_USER: "root"
        DB_PASSWORD: "root"
        DB_NAME: "root"
        DB_PORT: "5432"
